const english = {
    prevent: 'FIRE',
    person: 'INJURY',
    emegencyill: 'EMERGENCY ILLNESS',
    trafficaccident: 'TRAFFIC ACCIDENT',
    burglary: 'BURGLARY',
    theft: 'THEFT',
    violance: 'SELECTION & HOT',
    robbery: 'ROBBERY',
    computer: 'COMPUTER',
    waterdamage: 'WATERDAMAGE',
    electricaccident: 'ELECTRICACCIDENT',
    drowning: 'DROWNING',
    lostperson: 'LOSTPERSON',
    naturaldisasters: 'NATURALDISASTER',
    terrorism: 'TERRORISM',
    garbagesorting: 'GARBAGESORTING',
    worksafety: 'WORKSAFETY',
    travelsecurity: 'TRAVELSECURITY',
    crisispreparing: 'CRISISPREPARING',
    seasons: 'SEASONS',
    search: 'Search in app...',
    dashboard: 'Dashboard',
    forebygga: 'Prevent',
    akut: 'Emergency',
    efter: 'After',
    contact: 'Contact',
    users: 'Total users',
    main: 'Content',
    feature: 'Features',
    pushMsg: 'Push Messaging',
    auto: 'Automatic',
    autoMail: 'Automatic mailing',
    emerMail: 'Emergency mailing',
    advert: 'Advertising',
    welcomeNote: 'Welcome to Safe Private!',
    selectFunc: 'Select function in the menu on the left!',
    supportContact: 'For support, contact us:',
    epost: 'E-mail: ',
    notifylogs: 'Notification Logs',
    tel: 'Phone: ',
}

const swedish = {
    prevent: 'BRAND',
    person: 'PERSONSKADA',
    emegencyill: 'AKUT SJUKDOM',
    trafficaccident: 'TRAFIKOLYCKA',
    burglary: 'INBROTT',
    theft: 'STOLD',
    violance: 'VALD & HOT',
    robbery: 'RAN',
    computer: 'IT-SKADA',
    waterdamage: 'VVS-SKADA',
    electricaccident: 'ELOLYCKA',
    drowning: 'VATTENOLYCKA',
    lostperson: 'FORSVUNNEN',
    naturaldisasters: 'NATURKATASTROF',
    terrorism: 'TERRORISM',
    garbagesorting: 'MILJOSKADA',
    worksafety: 'ARBETSSKYDD',
    travelsecurity: 'RESESAKERHET',
    crisispreparing: 'KRISSEREDSKAP',
    seasons: 'SASONG',
    dashboard: 'Startsida',
    forebygga: 'Förebygga',
    akut: 'AKUT',
    efter: 'Efter',
    contact: 'Kontakter',
    search: 'Sök ...',
    users: 'Användare',
    main: 'Innehåll',
    feature: 'Funktioner',
    pushMsg: 'Pushmeddelanden',
    auto: 'Automatiska',
    autoMail: 'Automatiska utskick',
    emerMail: 'Akuta utskick',
    advert: 'Annonsering',
    welcomeNote: 'Välkommen till Tryggare Privat!',
    selectFunc: 'Välj funktion i menyn till vänster!',
    supportContact: 'För support, kontakta oss:',
    epost: 'Epost: ',
    tel: 'Tel: ',
    notifylogs: 'Meddelande loggar',

}

const languages = {
    english,
    swedish
}

export default languages